version: "3.9"

services:

  caddy:
    image: "docker.io/hectorm/caddy:latest"
    restart: "on-failure:3"
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile:ro"
      - "www:/var/www/goaccess/:ro"
      - "log:/var/log/caddy/"
    ports:
      - "0.0.0.0:8080:80/tcp"
      - "127.0.0.1:7890:7890/tcp"
    entrypoint: "/bin/sh"
    command: |
      -euc "
        touch /var/log/caddy/access.log
        exec caddy run --config /etc/caddy/Caddyfile --adapter caddyfile
      "

  goaccess:
    image: "docker.io/hectorm/goaccess:latest"
    restart: "on-failure:3"
    volumes:
      - "./goaccess.conf:/etc/goaccess/goaccess.conf:ro"
      - "www:/var/www/goaccess/"
      - "log:/var/log/caddy/:ro"
    depends_on:
      - "caddy"

volumes:

  www:
  log:
