version: "3.7"

services:

  caddy:
    image: "hectormolinero/caddy:latest"
    restart: "on-failure:3"
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile"
      - "www:/var/www/goaccess:ro"
      - "log:/var/log/caddy"
    ports:
      - "0.0.0.0:8080:80/tcp"
      - "127.0.0.1:7890:7890/tcp"
    depends_on:
      - "goaccess"

  goaccess:
    image: "hectormolinero/goaccess:latest"
    restart: "on-failure:3"
    volumes:
      - "./goaccess.conf:/etc/goaccess/goaccess.conf"
      - "www:/var/www/goaccess"
      - "log:/var/log/caddy:ro"

volumes:

  www:
  log:
